# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTFdQPUCoDnTrPpMOUeXUKjH3woHBATx
"""

import pandas as pd

# Leggi il file: imposta il separatore corretto (tab o virgola)
df_name=pd.read_csv("results_model_python.csv", sep=";")
df_model=pd.read_csv("results_name_python.csv", sep=";")

"""Per qualche motivo sono invertite. su df_name vedo Model prima, su df_model  vedo Name"""

df_model

df_name

#RF
RF_df=df_name[df_name["Model"]=="Random Forest"]
RF_df
mean_RF=RF_df['ACCURACY-oneshot'].mean()
print("Media RF:{}".format(mean_RF))

#SVM
SVM_df=df_name[df_name["Model"]=="SVM"]
SVM_df
mean_SVM=SVM_df['ACCURACY-oneshot'].mean()
print("Media SVM:{}".format(mean_SVM))

#XGBoost
XGB_df=df_name[df_name["Model"]=="XGBoost"]
XGB_df
mean_XGB=XGB_df['ACCURACY-oneshot'].mean()
print("Media XGB:{:2f}".format(mean_XGB))

# Crea una colonna "GruppoCompleto", es: "A2(5)"
df_name["Esp"] = df_name["Type of experiment"] + "(" + df_name["K"].astype(str) + ")"

df_name.loc[df_name["Type of experiment"] == "A1", "Esp"] = "A1"

mean_per_group = df_name.groupby("Esp")["ACCURACY-oneshot"].mean().sort_values()
mean_per_group

import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))
mean_per_group.plot(kind="bar", color="pink", edgecolor="black")
plt.xlabel("Tipo di esperimento")
plt.ylabel("Accuracy")
plt.title("Media per gruppo")
plt.show()